// Opening library. Each entry:
//   id, name, eco, tier (1 = most common … 4 = rare/esoteric),
//   color ("w" | "b") — the side the learner plays,
//   idea — short strategic summary,
//   moves — full mainline as { uci, note } pairs (note annotates that ply).
// Depth segments for progressive disclosure are derived in srs.js from move count.

const OPENINGS = [
    // ───────────────────────── Tier 1 — bread and butter ─────────────────────────
    {
        id: "ruy-lopez", name: "Ruy López", eco: "C65", tier: 1, color: "w",
        idea: "Pressure Black's knight on c6 to undermine the e5 pawn, then build a broad centre. The backbone of classical 1.e4 e5 play.",
        moves: [
            { uci: "e2e4", note: "Stake the centre." },
            { uci: "e7e5", note: "Black mirrors." },
            { uci: "g1f3", note: "Attack e5 and develop." },
            { uci: "b8c6", note: "Defend e5." },
            { uci: "f1b5", note: "The Ruy López bishop pins the defender of e5." },
            { uci: "a7a6", note: "Morphy's move — question the bishop." },
            { uci: "b5a4", note: "Maintain the pin." },
            { uci: "g8f6", note: "Develop and hit e4." },
            { uci: "e1g1", note: "Castle; the e4 pawn is indirectly defended." },
            { uci: "f8e7", note: "Calm development, preparing to castle." },
        ],
    },
    {
        id: "italian", name: "Italian Game", eco: "C50", tier: 1, color: "w",
        idea: "The bishop eyes f7, Black's weakest point. A natural, flexible setup that's ideal for learning open-game principles.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "e7e5", note: "Symmetry." },
            { uci: "g1f3", note: "Develop, attack e5." },
            { uci: "b8c6", note: "Defend." },
            { uci: "f1c4", note: "Aim the bishop at f7." },
            { uci: "f8c5", note: "Giuoco Piano — Black points back at f2." },
            { uci: "c2c3", note: "Prepare d4 to build the centre." },
            { uci: "g8f6", note: "Develop and pressure e4." },
            { uci: "d2d3", note: "Solid; support e4 and free the bishop." },
        ],
    },
    {
        id: "qgd", name: "Queen's Gambit Declined", eco: "D37", tier: 1, color: "w",
        idea: "Offer the c-pawn to deflect Black's d5; if declined, enjoy a space edge and easy development. A cornerstone of 1.d4 play.",
        moves: [
            { uci: "d2d4", note: "Claim the centre." },
            { uci: "d7d5", note: "Black contests it." },
            { uci: "c2c4", note: "The Queen's Gambit — pressure d5." },
            { uci: "e7e6", note: "Declined; solidify d5." },
            { uci: "b1c3", note: "Add pressure to d5." },
            { uci: "g8f6", note: "Develop, defend d5." },
            { uci: "c1g5", note: "Pin the knight, increase pressure." },
            { uci: "f8e7", note: "Break the pin's sting, prepare to castle." },
        ],
    },
    {
        id: "london", name: "London System", eco: "D02", tier: 1, color: "w",
        idea: "A reliable, low-theory setup: pawns on d4/e3, bishop out to f4 before e3. Easy to play, hard to crack.",
        moves: [
            { uci: "d2d4", note: "Centre." },
            { uci: "d7d5", note: "Black stakes a claim." },
            { uci: "g1f3", note: "Flexible development." },
            { uci: "g8f6", note: "Symmetry." },
            { uci: "c1f4", note: "The London bishop — out before locking it in with e3." },
            { uci: "e7e6", note: "Solid, but now Black's own bishop is hemmed in." },
            { uci: "e2e3", note: "Support d4, complete the pawn triangle." },
            { uci: "c7c5", note: "Strike at the base of the centre." },
        ],
    },
    {
        id: "sicilian-najdorf", name: "Sicilian — Najdorf", eco: "B90", tier: 1, color: "b",
        idea: "The sharpest, most respected answer to 1.e4. …a6 prepares …e5 and queenside expansion while denying White's pieces the b5 square.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "c7c5", note: "The Sicilian — fight for d4 asymmetrically." },
            { uci: "g1f3", note: "Develop." },
            { uci: "d7d6", note: "Support a future …e5 and free the c8 bishop." },
            { uci: "d2d4", note: "Open the centre." },
            { uci: "c5d4", note: "Trade the c-pawn for the d-pawn." },
            { uci: "f3d4", note: "Recapture; White has a lead in development." },
            { uci: "g8f6", note: "Develop, hit e4." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "a7a6", note: "The Najdorf move — controls b5, prepares …e5/…b5." },
        ],
    },
    {
        id: "caro-kann", name: "Caro-Kann Defence", eco: "B18", tier: 1, color: "b",
        idea: "Challenge e4 with …c6 and …d5 while keeping the light-squared bishop free — solid and resilient, without the cramp of the French.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "c7c6", note: "Prepare …d5 with pawn support." },
            { uci: "d2d4", note: "Big centre." },
            { uci: "d7d5", note: "Strike at e4 immediately." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "d5e4", note: "Resolve the tension." },
            { uci: "c3e4", note: "Recapture." },
            { uci: "c8f5", note: "Develop the bishop outside the pawn chain — the point of the Caro." },
        ],
    },
    {
        id: "french", name: "French Defence — Winawer", eco: "C18", tier: 1, color: "b",
        idea: "A combative French where …Bb4 pins the knight and trades structure for sharp imbalances. Solid yet ambitious.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "e7e6", note: "Prepare …d5; the French." },
            { uci: "d2d4", note: "Big centre." },
            { uci: "d7d5", note: "Challenge e4." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "f8b4", note: "The Winawer — pin the knight to pressure e4." },
        ],
    },
    {
        id: "qga", name: "Queen's Gambit Accepted", eco: "D20", tier: 1, color: "b",
        idea: "Take the c-pawn and aim for quick development and …c5/…e6 breaks, conceding the centre temporarily for free piece play.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "d7d5", note: "Contest it." },
            { uci: "c2c4", note: "The gambit." },
            { uci: "d5c4", note: "Accepted — grab the pawn (not to hold, but to deflect)." },
            { uci: "g1f3", note: "Stop …e5, develop." },
            { uci: "g8f6", note: "Develop, control e4." },
            { uci: "e2e3", note: "Regain the pawn with Bxc4 next." },
            { uci: "e7e6", note: "Open lines for the bishop, prepare …c5." },
        ],
    },

    // ───────────────────────── Tier 2 — common club play ─────────────────────────
    {
        id: "sicilian-dragon", name: "Sicilian — Dragon", eco: "B70", tier: 2, color: "b",
        idea: "Fianchetto the bishop to g7 where it rakes the long diagonal. Razor-sharp opposite-side castling battles.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "c7c5", note: "Sicilian." },
            { uci: "g1f3", note: "Develop." },
            { uci: "d7d6", note: "Support …e5/…g6 setups." },
            { uci: "d2d4", note: "Open the centre." },
            { uci: "c5d4", note: "Trade." },
            { uci: "f3d4", note: "Recapture." },
            { uci: "g8f6", note: "Hit e4." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "g7g6", note: "The Dragon — prepare …Bg7 on the long diagonal." },
        ],
    },
    {
        id: "sicilian-classical", name: "Sicilian — Classical", eco: "B56", tier: 2, color: "b",
        idea: "Develop knights naturally to c6 and f6 and contest the centre with piece pressure rather than committing pawns early.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "c7c5", note: "Sicilian." },
            { uci: "g1f3", note: "Develop." },
            { uci: "b8c6", note: "Classical development, eyeing d4." },
            { uci: "d2d4", note: "Open the centre." },
            { uci: "c5d4", note: "Trade." },
            { uci: "f3d4", note: "Recapture." },
            { uci: "g8f6", note: "Hit e4." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "d7d6", note: "Solid, restraining e5 and freeing the bishop." },
        ],
    },
    {
        id: "kings-indian", name: "King's Indian Defence", eco: "E70", tier: 2, color: "b",
        idea: "Let White build a big centre, then demolish it with …e5 or …c5 and a kingside pawn storm. Dynamic and aggressive.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "g8f6", note: "Control e4, stay flexible." },
            { uci: "c2c4", note: "Grab queenside space." },
            { uci: "g7g6", note: "Prepare the King's Indian fianchetto." },
            { uci: "b1c3", note: "Develop, support e4." },
            { uci: "f8g7", note: "The KID bishop eyes the long diagonal." },
            { uci: "e2e4", note: "White builds a broad pawn centre." },
            { uci: "d7d6", note: "Prepare the …e5 break against the centre." },
        ],
    },
    {
        id: "english", name: "English Opening", eco: "A20", tier: 2, color: "w",
        idea: "A flexible flank opening — 1.c4 controls d5 and can transpose widely. Often a reversed Sicilian with an extra tempo.",
        moves: [
            { uci: "c2c4", note: "Control d5 from the flank." },
            { uci: "e7e5", note: "A reversed Sicilian setup." },
            { uci: "b1c3", note: "Develop, fight for d5." },
            { uci: "g8f6", note: "Mirror." },
            { uci: "g1f3", note: "Pressure e5." },
            { uci: "b8c6", note: "Defend." },
            { uci: "g2g3", note: "Prepare the fianchetto that defines the English." },
        ],
    },
    {
        id: "scotch", name: "Scotch Game", eco: "C45", tier: 2, color: "w",
        idea: "Open the centre immediately with d4. Trades the cramping potential of the Italian for clear, active piece play.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "e7e5", note: "Symmetry." },
            { uci: "g1f3", note: "Attack e5." },
            { uci: "b8c6", note: "Defend." },
            { uci: "d2d4", note: "The Scotch — open the centre at once." },
            { uci: "e5d4", note: "Black accepts the trade." },
            { uci: "f3d4", note: "Recapture with a strong central knight." },
            { uci: "g8f6", note: "Develop, strike at e4." },
        ],
    },
    {
        id: "slav", name: "Slav Defence", eco: "D10", tier: 2, color: "b",
        idea: "Support d5 with …c6 while keeping the light bishop's diagonal open — the soundest way to meet the Queen's Gambit.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "d7d5", note: "Contest it." },
            { uci: "c2c4", note: "Queen's Gambit." },
            { uci: "c7c6", note: "The Slav — defend d5 without blocking the c8 bishop." },
            { uci: "g1f3", note: "Develop." },
            { uci: "g8f6", note: "Develop, guard d5." },
            { uci: "b1c3", note: "Pile on d5." },
            { uci: "d5c4", note: "Take, intending …b5 to hold the pawn temporarily." },
        ],
    },
    {
        id: "nimzo-indian", name: "Nimzo-Indian Defence", eco: "E20", tier: 2, color: "b",
        idea: "Pin and trade the c3 knight to inflict doubled pawns and control e4 with pieces — a strategic masterpiece of an opening.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "g8f6", note: "Control e4." },
            { uci: "c2c4", note: "Queenside space." },
            { uci: "e7e6", note: "Open lines for the bishop." },
            { uci: "b1c3", note: "Prepare e4." },
            { uci: "f8b4", note: "The Nimzo pin — fight for e4 by tying down the knight." },
        ],
    },
    {
        id: "pirc", name: "Pirc Defence", eco: "B07", tier: 2, color: "b",
        idea: "A hypermodern setup — concede the centre, fianchetto, and counterattack the overextended pawns later.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "d7d6", note: "Flexible, prepare …Nf6 and …g6." },
            { uci: "d2d4", note: "Big centre." },
            { uci: "g8f6", note: "Attack e4." },
            { uci: "b1c3", note: "Defend e4." },
            { uci: "g7g6", note: "Fianchetto to pressure the centre from afar." },
        ],
    },

    // ───────────────────────── Tier 3 — specialised ─────────────────────────
    {
        id: "grunfeld", name: "Grünfeld Defence", eco: "D80", tier: 3, color: "b",
        idea: "Invite a huge White centre, then chip away at it with …d5 and piece pressure on d4. Demands precise theory.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "g8f6", note: "Control e4." },
            { uci: "c2c4", note: "Queenside space." },
            { uci: "g7g6", note: "Prepare the fianchetto." },
            { uci: "b1c3", note: "Support e4." },
            { uci: "d7d5", note: "The Grünfeld strike — challenge the centre before fianchettoing." },
        ],
    },
    {
        id: "scandinavian", name: "Scandinavian Defence", eco: "B01", tier: 3, color: "b",
        idea: "Trade off the e-pawn immediately and develop with tempo. Direct and low-theory, if slightly passive.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "d7d5", note: "Challenge e4 at once." },
            { uci: "e4d5", note: "White takes." },
            { uci: "d8d5", note: "Recapture with the queen." },
            { uci: "b1c3", note: "Develop with tempo, hitting the queen." },
            { uci: "d5a5", note: "The main retreat — keep the queen active." },
        ],
    },
    {
        id: "vienna", name: "Vienna Game", eco: "C25", tier: 3, color: "w",
        idea: "A delayed King's Gambit idea — develop the knight first, then push f4 with extra support. Aggressive but sound.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "e7e5", note: "Symmetry." },
            { uci: "b1c3", note: "The Vienna — develop before committing the f-pawn." },
            { uci: "g8f6", note: "Develop, hit e4." },
            { uci: "f2f4", note: "The Vienna Gambit — strike with extra support behind it." },
        ],
    },
    {
        id: "kings-gambit", name: "King's Gambit", eco: "C30", tier: 3, color: "w",
        idea: "A romantic-era gambit — sacrifice the f-pawn for rapid development and a kingside attack. Wild and double-edged.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "e7e5", note: "Symmetry." },
            { uci: "f2f4", note: "The King's Gambit — offer the f-pawn for the centre and open lines." },
            { uci: "e5f4", note: "Accepted." },
            { uci: "g1f3", note: "Develop, stop …Qh4+, prepare to regain the pawn." },
        ],
    },
    {
        id: "alekhine", name: "Alekhine Defence", eco: "B02", tier: 3, color: "b",
        idea: "Provoke White's pawns forward, then attack the overextended chain. A hypermodern, counterpunching choice.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "g8f6", note: "Provoke e5 by attacking the pawn." },
            { uci: "e4e5", note: "White chases the knight." },
            { uci: "f6d5", note: "Hop to a strong square." },
            { uci: "d2d4", note: "Build the broad centre Black wants to attack." },
            { uci: "d7d6", note: "Strike at the head of the chain." },
        ],
    },
    {
        id: "benoni", name: "Modern Benoni", eco: "A60", tier: 3, color: "b",
        idea: "Unbalance the pawn structure for dynamic counterplay down the half-open e-file and the long diagonal. High risk, high reward.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "g8f6", note: "Control e4." },
            { uci: "c2c4", note: "Queenside space." },
            { uci: "c7c5", note: "The Benoni — challenge d4 asymmetrically." },
            { uci: "d4d5", note: "White locks the centre." },
            { uci: "e7e6", note: "Undermine the d5 pawn at once." },
        ],
    },
    {
        id: "catalan", name: "Catalan Opening", eco: "E00", tier: 3, color: "w",
        idea: "Combine a Queen's Gambit centre with a fianchettoed bishop that pressures d5 and the long diagonal. Positional and squeezing.",
        moves: [
            { uci: "d2d4", note: "Centre." },
            { uci: "g8f6", note: "Control e4." },
            { uci: "c2c4", note: "Queenside space." },
            { uci: "e7e6", note: "Solid, opens the bishop." },
            { uci: "g2g3", note: "The Catalan — fianchetto to bear down on d5." },
            { uci: "d7d5", note: "Black challenges the centre." },
            { uci: "f1g2", note: "Complete the bishop's setup on the long diagonal." },
        ],
    },
    {
        id: "dutch", name: "Dutch Defence", eco: "A80", tier: 3, color: "b",
        idea: "Fight for e4 with the f-pawn and aim for a kingside attack. Combative and asymmetric, with some structural risk.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "f7f5", note: "The Dutch — grab e4 and aim for a kingside game." },
            { uci: "g2g3", note: "White fianchettoes to blunt the attack." },
            { uci: "g8f6", note: "Develop." },
            { uci: "f1g2", note: "Contest the long diagonal." },
        ],
    },

    // ───────────────────────── Tier 4 — rare / esoteric ─────────────────────────
    {
        id: "birds", name: "Bird's Opening", eco: "A02", tier: 4, color: "w",
        idea: "A reversed Dutch — 1.f4 grabs e5 and aims for a kingside setup. Offbeat, with a slight kingside weakness.",
        moves: [
            { uci: "f2f4", note: "Bird's — control e5 from the flank." },
            { uci: "d7d5", note: "Black takes the centre." },
            { uci: "g1f3", note: "Develop, control e5." },
            { uci: "g8f6", note: "Mirror." },
            { uci: "e2e3", note: "Open the bishop, support f4." },
        ],
    },
    {
        id: "larsen", name: "Nimzowitsch-Larsen Attack", eco: "A01", tier: 4, color: "w",
        idea: "Fianchetto the queen's bishop first with 1.b3, pressuring e5 and the long diagonal. Hypermodern and provocative.",
        moves: [
            { uci: "b2b3", note: "Prepare the queenside fianchetto." },
            { uci: "e7e5", note: "Black grabs the centre." },
            { uci: "c1b2", note: "The point — pressure e5 along the long diagonal." },
            { uci: "b8c6", note: "Defend e5." },
            { uci: "e2e3", note: "Restrained, flexible development." },
        ],
    },
    {
        id: "polish", name: "Polish (Sokolsky)", eco: "A00", tier: 4, color: "w",
        idea: "1.b4 grabs queenside space and fianchettoes the bishop. Genuinely offbeat — surprise value over soundness.",
        moves: [
            { uci: "b2b4", note: "The Orangutan — seize queenside space." },
            { uci: "e7e5", note: "Black takes the centre and eyes b4." },
            { uci: "c1b2", note: "Fianchetto, attacking e5." },
            { uci: "f8b4", note: "Black wins the pawn — White gambits for the diagonal." },
        ],
    },
    {
        id: "scandi-gambit", name: "Danish Gambit", eco: "C21", tier: 4, color: "w",
        idea: "Sacrifice one or two pawns for blazing development and bishops raking toward f7. Pure romantic chess.",
        moves: [
            { uci: "e2e4", note: "Centre." },
            { uci: "e7e5", note: "Symmetry." },
            { uci: "d2d4", note: "Open the centre." },
            { uci: "e5d4", note: "Black takes." },
            { uci: "c2c3", note: "The Danish — offer a second pawn for a huge lead in development." },
        ],
    },
    {
        id: "englund", name: "Englund Gambit", eco: "A40", tier: 4, color: "b",
        idea: "A dubious but tricky pawn sac against 1.d4, banking on quick development and traps. Strictly a surprise weapon.",
        moves: [
            { uci: "d2d4", note: "White's centre." },
            { uci: "e7e5", note: "The Englund Gambit — sacrifice a pawn to open lines fast." },
            { uci: "d4e5", note: "White accepts." },
            { uci: "b8c6", note: "Develop, target the e5 pawn." },
            { uci: "g1f3", note: "Defend e5." },
            { uci: "d8e7", note: "Pile on e5 and prepare tricks on the e-file." },
        ],
    },
    {
        id: "owens", name: "Owen's Defence", eco: "B00", tier: 4, color: "b",
        idea: "Fianchetto immediately with …b6 to fight for e4 from the flank. Provocative and rarely seen at top level.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "b7b6", note: "Owen's — prepare …Bb7 against e4." },
            { uci: "d2d4", note: "White builds the centre." },
            { uci: "c8b7", note: "The bishop bears down on e4 and g2." },
            { uci: "f1d3", note: "Defend e4." },
            { uci: "e7e6", note: "Flexible, supports …d5 or …c5 breaks." },
        ],
    },
    {
        id: "st-george", name: "St. George Defence", eco: "B00", tier: 4, color: "b",
        idea: "An ultra-offbeat …a6/…b5 plan made famous by Miles' win over Karpov. Almost never sound, but full of surprise.",
        moves: [
            { uci: "e2e4", note: "White's centre." },
            { uci: "a7a6", note: "The St. George — a quiet prelude to …b5." },
            { uci: "d2d4", note: "White grabs the full centre." },
            { uci: "b7b5", note: "Queenside expansion, the whole point of the line." },
        ],
    },
    {
        id: "grob", name: "Grob's Attack", eco: "A00", tier: 4, color: "w",
        idea: "1.g4 — perhaps the most notorious opening in chess. Weakens the kingside badly but can shock an unprepared opponent.",
        moves: [
            { uci: "g2g4", note: "The Grob — lash out on the kingside (objectively dubious)." },
            { uci: "d7d5", note: "Black takes the centre and eyes g4." },
            { uci: "f1g2", note: "Fianchetto, pressuring d5." },
            { uci: "c7c6", note: "Defend d5 solidly." },
        ],
    },
];

window.OPENINGS = OPENINGS;
